name: Generate Repository Social Preview Card

# Define the events that trigger this workflow
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub UI

# The 'jobs' section is required to define the work to be done
jobs:
  generate_preview_card:
    # CRITICAL: Only run this workflow if the push was NOT made by the 'github-actions[bot]' user.
    # This prevents an infinite loop when the action commits the new files.
    if: github.actor != 'github-actions[bot]'

    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest
    
    # Grant permission for this specific job to commit files back to the repository
    permissions:
      contents: write

    steps:
      - name: Checkout repository code
        # Uses an official GitHub action to download your repository content
        uses: actions/checkout@v4

      - name: Setup Node.js
        # Sets up the Node.js environment needed to run your JavaScript script
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      # --- CRITICAL: Install System Dependencies for Puppeteer/Chromium ---
      - name: Install Chromium Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libxkbcommon-x11-0 libgbm-dev
          
      # --- Install dependencies (puppeteer, simple-git) ---
      - name: Install Node Dependencies (Use npm ci for faster, reproducible CI builds)
        run: npm ci

      # --- STEP A: AUTOMATIC IMAGE GENERATION SCRIPT EXECUTION ---
      - name: Generate Preview Image via Node.js Script
        run: node generate_preview_script.js
        env:
          # Passes the GITHUB_TOKEN to the Node.js script for API calls (fetching repos)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      # --- STEP B: Commit and Push the New File ---
      - name: Check for changes and commit
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: Auto-generated social media preview cards'
          # Commit all files inside the new 'previews/' directory
          file_pattern: previews/*
          # The 'token' input was removed here as it is no longer needed/accepted by V5.

      - name: Report Status
        if: steps.commit.outputs.changes_detected == 'true'
        run: echo "Successfully generated and committed preview files in previews/ directory."

      - name: Report No Changes
        if: steps.commit.outputs.changes_detected == 'false'
        run: echo "No changes detected, skipping commit."
