name: Generate Repository Social Preview Card

# Define the events that trigger this workflow
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub UI

# The 'jobs' section is required to define the work to be done
jobs:
  generate_preview_card:
    # CRITICAL FIX: Only run this workflow if the push was NOT made by the 'github-actions[bot]' user.
    # This prevents an infinite loop and avoids interference with other jobs (like Pages builds).
    if: github.actor != 'github-actions[bot]'

    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest
    
    # Grant permission for this specific job to commit files back to the repository
    permissions:
      contents: write

    steps:
      - name: Checkout repository code
        # Uses an official GitHub action to download your repository content
        uses: actions/checkout@v4

      - name: Setup Node.js
        # Sets up the Node.js environment needed to run your JavaScript script
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      # --- Install dependencies (puppeteer, simple-git, rimraf) ---
      - name: Install Node Dependencies
        run: npm install

      # --- STEP A: AUTOMATIC IMAGE GENERATION SCRIPT EXECUTION ---
      # This step executes the 'generate_preview_script.js' file in the root of your repo
      - name: Generate Preview Image via Node.js Script
        run: node generate_preview_script.js
        # The script creates multiple image files inside the new 'previews/' directory.

      # --- STEP B: Commit and Push the New File ---
      # This action checks if the 'previews/' directory was created or modified and commits it.
      - name: Check for changes and commit
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: Auto-generated social media preview cards'
          # CRITICAL FIX: Commit all files inside the new 'previews/' directory
          file_pattern: previews/*
          # CRITICAL FIX: The token is needed for cloning other repos and for the commit action itself
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Report Status
        if: steps.commit.outputs.changes_detected == 'true'
        run: echo "Successfully generated and committed preview files in previews/ directory."

      - name: Report No Changes
        if: steps.commit.outputs.changes_detected == 'false'
        run: echo "No changes detected, skipping commit."
